### ISSUE TITLE
Drag and drop for angular components

### ISSUE THREAD

**Issue by sorayaM** [4teamwork/cypress-drag-drop#33] opened 2020-02-25 18:42 UTC
Is there a way to apply the d&d for angular components?

**Comment by bierik** [comment] 2020-04-16 08:42
@sorayaM I think this issue is already discussed in https://github.com/4teamwork/cypress-drag-drop/issues/24.

**Comment by bierik** [comment] 2020-12-10 13:47
Duplicate of https://github.com/4teamwork/cypress-drag-drop/issues/24

**Closed by bierik** 2020-12-10 13:47 UTC
Labels: angular
